os:
  - linux
language: generic
sudo: required
dist: trusty
env:
  - SWIFT_VERSION=5.0 SWIFTENV_ROOT="$HOME/.swiftenv" PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
install:
  - ./scripts/install_swiftenv.sh
script:
  - swift build
