os:
  - linux
language: generic
sudo: required
dist: xenial
env:
  - SWIFT_VERSION=5.5 SWIFTENV_ROOT="$HOME/.swiftenv" PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
install:
  - ./scripts/install_swiftenv.sh
script:
  - swift test
