version: 2.1

jobs:
  xcode_13_2:
    macos:
      xcode: 13.2
    steps:
      - checkout
      - run:
          name: "Build"
          command: "swift build"
  xcode_13_3:
    macos:
      xcode: 13.3
    steps:
      - checkout
      - run:
          name: "Build"
          command: "swift build"
  xcode_13_4:
    macos:
      xcode: 13.4
    steps:
      - checkout
      - run:
          name: "Build"
          command: "swift build"
      - run:
          name: "Test"
          command: "swift test"
  xcode_14_1:
    macos:
      xcode: 14.1
    steps:
      - checkout
      - run:
          name: "Build"
          command: "swift build"
      - run:
          name: "Test"
          command: "swift test"
  xcode_14_2:
    macos:
      xcode: 14.2
    steps:
      - checkout
      - run:
          name: "Build"
          command: "swift build"
      - run:
          name: "Test"
          command: "swift test"


workflows:
  build-and-test:
    jobs:
      - xcode_13_2
      - xcode_13_3
      - xcode_13_4
      - xcode_14_1
      - xcode_14_2
