version: 2.1

jobs:
  build_and_test:
    parameters:
      xcode_version:
        type: string
    macos:
      xcode: << parameters.xcode_version >>
    steps:
      - checkout
      - run:
          name: "Build"
          command: swift build
      - run:
          name: "Test"
          command: swift test


workflows:
  build-and-test:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              xcode_version: [13.4.1, 14.3.1, 15.1.0]
